// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY4NGZHhszseQrjXylQNpINrB6CnFkFs',
    appId: '1:896401038168:web:1d9f2419263c6d4151632d',
    messagingSenderId: '896401038168',
    projectId: 'sneaker-app-a434e',
    authDomain: 'sneaker-app-a434e.firebaseapp.com',
    storageBucket: 'sneaker-app-a434e.appspot.com',
    measurementId: 'G-KR9FWJMP93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNBccxEKYE_vMxRZwGwVL4oOOx2-_PLs',
    appId: '1:896401038168:android:f89e40ab9e7c516251632d',
    messagingSenderId: '896401038168',
    projectId: 'sneaker-app-a434e',
    storageBucket: 'sneaker-app-a434e.appspot.com',
  );
}
